# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: ptbxl
  - /task: multilabel_classification
  - /optimizer: adamw
  - /scheduler: plateau

train:
  monitor: val/loss
  mode: min

encoder: linear

decoder:
  _name_: sequence
  mode: pool

task:
  metrics:
    - binary_accuracy
