_name_: local_window_copying
l_seq: 4096           # length of continuous input signal
l_window_min: 16      # minimum length of window to reconstruct
l_window_max: 128     # maximum length of window to reconstruct
query_length: 1       # number of query steps appended after the signal
dt: 0.001
freq: 2.0
static: false         # keep sampling new sequences each epoch
n_train: 10000
n_eval: 1000
__l_max: ${eval:${.l_seq}+${.query_length}}
