_name_: ptbxl
sampling_rate: 100
duration: 10
nleads: 12
ctype: superdiagnostic
min_samples: 0
data_dir: ${oc.env:DATA_PATH,${hydra:runtime.cwd}/data}/ptbxl
__l_max: ${eval:${.sampling_rate}*${.duration}}
